"""
CounterAgent Polynomial: State machine definition.

States: IDLE, ACTIVE, ERROR
Initial: IDLE

Auto-generated by the Metaphysical Forge.
"""

from dataclasses import dataclass
from enum import Enum
from typing import Any


class CounterAgentState(str, Enum):
    """States for CounterAgent."""

    IDLE = "idle"
    ACTIVE = "active"
    ERROR = "error"


# State transition map
COUNTERAGENT_TRANSITIONS: dict[CounterAgentState, list[CounterAgentState]] = {
    CounterAgentState.IDLE: [CounterAgentState.ACTIVE],
    CounterAgentState.ACTIVE: [CounterAgentState.IDLE, CounterAgentState.ERROR],
    CounterAgentState.ERROR: [CounterAgentState.IDLE],
}


@dataclass
class CounterAgentPolynomial:
    """
    PolyAgent polynomial for CounterAgent.

    Laws:
    - Identity: agent >> identity = agent
    - Graceful degradation: ERROR → IDLE always valid
    """

    state: CounterAgentState = CounterAgentState.IDLE

    def can_transition(self, to_state: CounterAgentState) -> bool:
        """Check if transition is valid."""
        valid_transitions = COUNTERAGENT_TRANSITIONS.get(self.state, [])
        return to_state in valid_transitions

    def transition(self, to_state: CounterAgentState) -> bool:
        """Attempt state transition. Returns True if successful."""
        if self.can_transition(to_state):
            self.state = to_state
            return True
        return False


__all__ = ["CounterAgentState", "CounterAgentPolynomial", "COUNTERAGENT_TRANSITIONS"]
