"""
Witness Crown Jewel: Primitives for Witnessing, Memory, and Trust.

The Witness service provides:
- Mark: Atomic unit of witnessed execution
- Grant: Permission contracts
- Scope: Budget and context constraints
- Playbook: Lawful workflow orchestration
- Lesson: Immutable curated knowledge

The daemon infrastructure (CLI, watchers, pipelines) has moved to services/kgentsd/.

Philosophy:
    "The proof IS the decision. The mark IS the witness."

See: docs/skills/metaphysical-fullstack.md
See: spec/services/witness.md
"""

from .contracts import (
    ActionRecordRequest,
    ActionRecordResponse,
    CaptureThoughtRequest,
    CaptureThoughtResponse,
    EscalateRequest,
    EscalateResponse,
    InvokeRequest,
    InvokeResponse,
    PipelineRequest,
    PipelineResponse,
    PipelineStepItem,
    PipelineStepResultItem,
    RollbackWindowRequest,
    RollbackWindowResponse,
    ThoughtsRequest,
    ThoughtsResponse,
    TrustRequest,
    TrustResponse,
    WitnessManifestResponse,
)
from .crystal import (
    ExperienceCrystal,
    MoodVector,
    Narrative,
    TopologySnapshot,
)
from .crystallization_node import (
    TimeWitnessManifestRendering,
    TimeWitnessManifestResponse,
    TimeWitnessNode,
)

# Grant (renamed from Covenant)
from .grant import (
    GateFallback,
    GateOccurrence,
    GateTriggered,
    Grant,
    GrantEnforcer,
    GrantError,
    GrantId,
    GrantNotGranted,
    GrantRevoked,
    GrantStatus,
    GrantStore,
    ReviewGate,
    generate_grant_id,
    get_grant_store,
    reset_grant_store,
)
from .intent import (
    CyclicDependencyError,
    Intent,
    IntentId,
    IntentStatus,
    IntentTree,
    IntentType,
    generate_intent_id,
    get_intent_tree,
    reset_intent_tree,
)

# Lesson (renamed from Terrace)
from .lesson import (
    Lesson,
    LessonId,
    LessonStatus,
    LessonStore,
    generate_lesson_id,
    get_lesson_store,
    reset_lesson_store,
    set_lesson_store,
)

# Mark (renamed from TraceNode)
from .mark import (
    EvidenceTier,
    LinkRelation,
    Mark,
    MarkId,
    MarkLink,
    NPhase,
    PlanPath,
    Proof,
    Response,
    Stimulus,
    UmweltSnapshot,
    WalkId,
    generate_mark_id,
)
from .node import (
    ThoughtStreamRendering,
    WitnessManifestRendering,
    WitnessNode,
)
from .operad import (
    WITNESS_OPERAD,
    compose_autonomous_workflow,
    compose_observe_workflow,
    compose_suggest_workflow,
    create_witness_operad,
)
from .persistence import (
    ActionResultPersisted,
    EscalationResult,
    ThoughtResult,
    TrustResult,
    WitnessPersistence,
    WitnessStatus,
)

# Playbook (renamed from Ritual)
from .playbook import (
    GuardEvaluation,
    GuardFailed,
    GuardResult,
    InvalidPhaseTransition,
    MissingGrant,
    MissingScope,
    Playbook,
    PlaybookError,
    PlaybookId,
    PlaybookNotActive,
    PlaybookPhase,
    PlaybookStatus,
    PlaybookStore,
    SentinelGuard,
    generate_playbook_id,
    get_playbook_store,
    reset_playbook_store,
)
from .polynomial import (
    WITNESS_POLYNOMIAL,
    ActionResult,
    AgenteseEvent,
    CIEvent,
    EscalateCommand,
    FileEvent,
    GitEvent,
    StartCommand,
    StopCommand,
    TestEvent,
    Thought,
    TrustLevel,
    WitnessInputFactory,
    WitnessOutput,
    WitnessPhase,
    WitnessPolynomial,
    WitnessState,
)

# Scope (renamed from Offering)
from .scope import (
    Budget,
    BudgetExceeded,
    HandleNotInScope,
    Scope,
    ScopeError,
    ScopeExpired,
    ScopeId,
    ScopeStatus,
    ScopeStore,
    generate_scope_id,
    get_scope_store,
    reset_scope_store,
)
from .session_walk import (
    SessionWalkBinding,
    SessionWalkBridge,
    get_session_walk_bridge,
    reset_session_walk_bridge,
)
from .sheaf import (
    SOURCE_CAPABILITIES,
    EventSource,
    GluingError,
    LocalObservation,
    WitnessSheaf,
    source_overlap,
    verify_associativity_law,
    verify_identity_law,
)

# MarkStore (renamed from TraceStore)
from .trace_store import (
    CausalityViolation,
    DuplicateMarkError,
    MarkNotFoundError,
    MarkQuery,
    MarkStore,
    MarkStoreError,
    get_mark_store,
    reset_mark_store,
    set_mark_store,
)
from .trust import (
    ActionGate,
    BoundaryChecker,
    BoundaryViolation,
    ConfirmationManager,
    ConfirmationResult,
    EscalationCheckResult,
    EscalationCriteria,
    GateDecision,
    GateResult,
    Level1Criteria,
    Level2Criteria,
    Level3Criteria,
    ObservationStats,
    OperationStats,
    PendingSuggestion,
    SuggestionStats,
    check_escalation,
)
from .voice_gate import (
    DENYLIST_PATTERNS,
    HEDGE_PATTERNS,
    VOICE_ANCHORS,
    VoiceAction,
    VoiceCheckResult,
    VoiceGate,
    VoiceRule,
    VoiceViolation,
    get_voice_gate,
    reset_voice_gate,
    set_voice_gate,
)
from .walk import (
    Participant,
    Walk,
    WalkIntent,
    WalkStatus,
    WalkStore,
    get_walk_store,
    reset_walk_store,
)

# Explicit exports for mypy
__all__ = [
    # Contracts
    "ActionRecordRequest",
    "ActionRecordResponse",
    "CaptureThoughtRequest",
    "CaptureThoughtResponse",
    "EscalateRequest",
    "EscalateResponse",
    "InvokeRequest",
    "InvokeResponse",
    "PipelineRequest",
    "PipelineResponse",
    "PipelineStepItem",
    "PipelineStepResultItem",
    "RollbackWindowRequest",
    "RollbackWindowResponse",
    "ThoughtsRequest",
    "ThoughtsResponse",
    "TrustRequest",
    "TrustResponse",
    "WitnessManifestResponse",
    # Crystal
    "ExperienceCrystal",
    "MoodVector",
    "Narrative",
    "TopologySnapshot",
    # Crystallization Node
    "TimeWitnessManifestRendering",
    "TimeWitnessManifestResponse",
    "TimeWitnessNode",
    # Grant (renamed from Covenant)
    "GateFallback",
    "GateOccurrence",
    "GateTriggered",
    "Grant",
    "GrantEnforcer",
    "GrantError",
    "GrantId",
    "GrantNotGranted",
    "GrantRevoked",
    "GrantStatus",
    "GrantStore",
    "ReviewGate",
    "generate_grant_id",
    "get_grant_store",
    "reset_grant_store",
    # Intent
    "CyclicDependencyError",
    "Intent",
    "IntentId",
    "IntentStatus",
    "IntentTree",
    "IntentType",
    "generate_intent_id",
    "get_intent_tree",
    "reset_intent_tree",
    # Lesson (renamed from Terrace)
    "Lesson",
    "LessonId",
    "LessonStatus",
    "LessonStore",
    "generate_lesson_id",
    "get_lesson_store",
    "reset_lesson_store",
    "set_lesson_store",
    # Mark (renamed from TraceNode)
    "EvidenceTier",
    "LinkRelation",
    "Mark",
    "MarkId",
    "MarkLink",
    "NPhase",
    "PlanPath",
    "Proof",
    "Response",
    "Stimulus",
    "UmweltSnapshot",
    "WalkId",
    "generate_mark_id",
    # Node
    "ThoughtStreamRendering",
    "WitnessManifestRendering",
    "WitnessNode",
    # Operad
    "WITNESS_OPERAD",
    "compose_autonomous_workflow",
    "compose_observe_workflow",
    "compose_suggest_workflow",
    "create_witness_operad",
    # Persistence
    "ActionResultPersisted",
    "EscalationResult",
    "ThoughtResult",
    "TrustResult",
    "WitnessPersistence",
    "WitnessStatus",
    # Playbook (renamed from Ritual)
    "GuardEvaluation",
    "GuardFailed",
    "GuardResult",
    "InvalidPhaseTransition",
    "MissingGrant",
    "MissingScope",
    "Playbook",
    "PlaybookError",
    "PlaybookId",
    "PlaybookNotActive",
    "PlaybookPhase",
    "PlaybookStatus",
    "PlaybookStore",
    "SentinelGuard",
    "generate_playbook_id",
    "get_playbook_store",
    "reset_playbook_store",
    # Polynomial
    "WITNESS_POLYNOMIAL",
    "ActionResult",
    "AgenteseEvent",
    "CIEvent",
    "EscalateCommand",
    "FileEvent",
    "GitEvent",
    "StartCommand",
    "StopCommand",
    "TestEvent",
    "Thought",
    "TrustLevel",
    "WitnessInputFactory",
    "WitnessOutput",
    "WitnessPhase",
    "WitnessPolynomial",
    "WitnessState",
    # Scope (renamed from Offering)
    "Budget",
    "BudgetExceeded",
    "HandleNotInScope",
    "Scope",
    "ScopeError",
    "ScopeExpired",
    "ScopeId",
    "ScopeStatus",
    "ScopeStore",
    "generate_scope_id",
    "get_scope_store",
    "reset_scope_store",
    # Session Walk
    "SessionWalkBinding",
    "SessionWalkBridge",
    "get_session_walk_bridge",
    "reset_session_walk_bridge",
    # Sheaf
    "SOURCE_CAPABILITIES",
    "EventSource",
    "GluingError",
    "LocalObservation",
    "WitnessSheaf",
    "source_overlap",
    "verify_associativity_law",
    "verify_identity_law",
    # Mark Store
    "CausalityViolation",
    "DuplicateMarkError",
    "MarkNotFoundError",
    "MarkQuery",
    "MarkStore",
    "MarkStoreError",
    "get_mark_store",
    "reset_mark_store",
    "set_mark_store",
    # Trust
    "ActionGate",
    "BoundaryChecker",
    "BoundaryViolation",
    "ConfirmationManager",
    "ConfirmationResult",
    "EscalationCheckResult",
    "EscalationCriteria",
    "GateDecision",
    "GateResult",
    "Level1Criteria",
    "Level2Criteria",
    "Level3Criteria",
    "ObservationStats",
    "OperationStats",
    "PendingSuggestion",
    "SuggestionStats",
    "check_escalation",
    # Voice Gate
    "DENYLIST_PATTERNS",
    "HEDGE_PATTERNS",
    "VOICE_ANCHORS",
    "VoiceAction",
    "VoiceCheckResult",
    "VoiceGate",
    "VoiceRule",
    "VoiceViolation",
    "get_voice_gate",
    "reset_voice_gate",
    "set_voice_gate",
    # Walk
    "Participant",
    "Walk",
    "WalkIntent",
    "WalkStatus",
    "WalkStore",
    "get_walk_store",
    "reset_walk_store",
]
