"""
TestAgent: Agent for: Test agent

Auto-generated by the Metaphysical Forge.
"""

from .polynomial import TestAgentPolynomial
from .service import TestService

__all__ = [
    "TestService",
    "TestAgentPolynomial",
]
