"""
TestFailureAgent Polynomial: State machine definition.

States: IDLE, ACTIVE, ERROR
Initial: IDLE

Auto-generated by the Metaphysical Forge.
"""

from dataclasses import dataclass
from enum import Enum
from typing import Any


class TestFailureAgentState(str, Enum):
    """States for TestFailureAgent."""

    IDLE = "idle"
    ACTIVE = "active"
    ERROR = "error"


# State transition map
TESTFAILUREAGENT_TRANSITIONS: dict[TestFailureAgentState, list[TestFailureAgentState]] = {
    TestFailureAgentState.IDLE: [TestFailureAgentState.ACTIVE],
    TestFailureAgentState.ACTIVE: [TestFailureAgentState.IDLE, TestFailureAgentState.ERROR],
    TestFailureAgentState.ERROR: [TestFailureAgentState.IDLE],
}


@dataclass
class TestFailureAgentPolynomial:
    """
    PolyAgent polynomial for TestFailureAgent.

    Laws:
    - Identity: agent >> identity = agent
    - Graceful degradation: ERROR → IDLE always valid
    """

    state: TestFailureAgentState = TestFailureAgentState.IDLE

    def can_transition(self, to_state: TestFailureAgentState) -> bool:
        """Check if transition is valid."""
        valid_transitions = TESTFAILUREAGENT_TRANSITIONS.get(self.state, [])
        return to_state in valid_transitions

    def transition(self, to_state: TestFailureAgentState) -> bool:
        """Attempt state transition. Returns True if successful."""
        if self.can_transition(to_state):
            self.state = to_state
            return True
        return False


__all__ = ["TestFailureAgentState", "TestFailureAgentPolynomial", "TESTFAILUREAGENT_TRANSITIONS"]
