"""
PreferencesAgent: Agent for: Build a preferences manager

Auto-generated by the Metaphysical Forge.
"""

from .polynomial import PreferencesAgentPolynomial
from .service import PreferencesService

__all__ = [
    "PreferencesService",
    "PreferencesAgentPolynomial",
]
