"""
TestAgent Polynomial: State machine definition.

States: IDLE, ACTIVE, ERROR
Initial: IDLE

Auto-generated by the Metaphysical Forge.
"""

from dataclasses import dataclass
from enum import Enum
from typing import Any


class TestAgentState(str, Enum):
    """States for TestAgent."""
        IDLE = "idle"
    ACTIVE = "active"
    ERROR = "error"


# State transition map
TESTAGENT_TRANSITIONS: dict[TestAgentState, list[TestAgentState]] = {
        TestAgentState.IDLE: [TestAgentState.ACTIVE],
    TestAgentState.ACTIVE: [TestAgentState.IDLE, TestAgentState.ERROR],
    TestAgentState.ERROR: [TestAgentState.IDLE],
}


@dataclass
class TestAgentPolynomial:
    """
    PolyAgent polynomial for TestAgent.

    Laws:
        - Identity: agent >> identity = agent
    - Graceful degradation: ERROR → IDLE always valid
    """

    state: TestAgentState = TestAgentState.IDLE

    def can_transition(self, to_state: TestAgentState) -> bool:
        """Check if transition is valid."""
        valid_transitions = TESTAGENT_TRANSITIONS.get(self.state, [])
        return to_state in valid_transitions

    def transition(self, to_state: TestAgentState) -> bool:
        """Attempt state transition. Returns True if successful."""
        if self.can_transition(to_state):
            self.state = to_state
            return True
        return False


__all__ = ["TestAgentState", "TestAgentPolynomial", "TESTAGENT_TRANSITIONS"]
