"""
PreferencesAgent Polynomial: State machine definition.

States: IDLE, ACTIVE, ERROR
Initial: IDLE

Auto-generated by the Metaphysical Forge.
"""

from dataclasses import dataclass
from enum import Enum
from typing import Any


class PreferencesAgentState(str, Enum):
    """States for PreferencesAgent."""

    IDLE = "idle"
    ACTIVE = "active"
    ERROR = "error"


# State transition map
PREFERENCESAGENT_TRANSITIONS: dict[PreferencesAgentState, list[PreferencesAgentState]] = {
    PreferencesAgentState.IDLE: [PreferencesAgentState.ACTIVE],
    PreferencesAgentState.ACTIVE: [PreferencesAgentState.IDLE, PreferencesAgentState.ERROR],
    PreferencesAgentState.ERROR: [PreferencesAgentState.IDLE],
}


@dataclass
class PreferencesAgentPolynomial:
    """
    PolyAgent polynomial for PreferencesAgent.

    Laws:
    - Identity: agent >> identity = agent
    - Graceful degradation: ERROR → IDLE always valid
    """

    state: PreferencesAgentState = PreferencesAgentState.IDLE

    def can_transition(self, to_state: PreferencesAgentState) -> bool:
        """Check if transition is valid."""
        valid_transitions = PREFERENCESAGENT_TRANSITIONS.get(self.state, [])
        return to_state in valid_transitions

    def transition(self, to_state: PreferencesAgentState) -> bool:
        """Attempt state transition. Returns True if successful."""
        if self.can_transition(to_state):
            self.state = to_state
            return True
        return False


__all__ = ["PreferencesAgentState", "PreferencesAgentPolynomial", "PREFERENCESAGENT_TRANSITIONS"]
