"""
Research Report Task Template.

Coalition Shape: Scout + Sage + 2 specialists
Output Format: Markdown
Credits: 50

The research report is the workhorse of Coalition Forge.
It demonstrates the full power of collaborative research.

Flow:
    1. Scout explores the research landscape
    2. Sage analyzes and synthesizes findings
    3. Specialists dive deep on specific aspects
    4. Output is compiled into structured markdown
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from ..task import (
    CoalitionShape,
    HandoffPattern,
    OutputFormat,
    TaskInput,
    TaskOutput,
)
from .base import TaskTemplate

# Coalition shape for research
RESEARCH_REPORT_SHAPE = CoalitionShape(
    required=("Scout", "Sage"),
    optional=("Spark", "Steady"),  # Specialists
    lead="Scout",
    pattern=HandoffPattern.SEQUENTIAL,
    min_eigenvector={"analytical": 0.7, "creativity": 0.3},
)


@dataclass
class ResearchReportTask(TaskTemplate):
    """
    Research Report: Deep research on any topic.

    Input: Topic description, scope, depth preference
    Output: Structured markdown report with sections:
        - Executive Summary
        - Key Findings
        - Detailed Analysis
        - Recommendations
        - Sources
    """

    template_id: ClassVar[str] = "research_report"
    name: ClassVar[str] = "Research Report"
    description: ClassVar[str] = (
        "Comprehensive research report on any topic. "
        "Scouts gather information, Sages synthesize, "
        "specialists dive deep."
    )
    base_credits: ClassVar[int] = 50
    output_format: ClassVar[OutputFormat] = OutputFormat.MARKDOWN

    coalition_shape: CoalitionShape = field(
        default_factory=lambda: RESEARCH_REPORT_SHAPE
    )

    def validate_input(self, input: TaskInput) -> tuple[bool, list[str]]:
        """Validate research-specific requirements."""
        is_valid, errors = super().validate_input(input)

        # Research benefits from a target
        if not input.target and "context" not in input.context:
            errors.append(
                "Research tasks work best with a target or context. "
                "Consider specifying what to research."
            )
            # This is a warning, not a blocker
            # is_valid remains unchanged

        return is_valid, errors

    def suggest_coalition(self, input: TaskInput) -> CoalitionShape:
        """Adjust coalition based on research depth."""
        shape = self.coalition_shape

        if input.depth == "deep":
            # Deep research adds more specialists
            return CoalitionShape(
                required=("Scout", "Sage", "Spark", "Steady"),
                optional=(),
                lead="Scout",
                pattern=HandoffPattern.SEQUENTIAL,
            )
        elif input.depth == "quick":
            # Quick research: just Scout + Sage
            return CoalitionShape(
                required=("Scout", "Sage"),
                optional=(),
                lead="Scout",
                pattern=HandoffPattern.SEQUENTIAL,
            )

        return shape

    def get_phase_sequence(self) -> list[str]:
        """Research follows: EXPLORING → DESIGNING → (REFINING)."""
        return ["EXPLORING", "DESIGNING", "REFINING"]

    def get_handoff_descriptions(self) -> dict[str, str]:
        """Describe expected handoffs."""
        return {
            "Scout→Sage": "Scout passes raw findings to Sage for analysis",
            "Sage→Specialist": "Sage identifies areas needing deep dives",
            "Specialist→Sage": "Specialist findings flow back for synthesis",
        }

    async def execute(
        self,
        input: TaskInput,
        coalition: Any,
    ) -> TaskOutput:
        """
        Execute research report generation.

        This is the orchestration logic that coordinates the coalition.
        """
        # Phase 1: Scout explores
        # Phase 2: Sage analyzes
        # Phase 3: Specialists dive
        # Phase 4: Compile output

        # For MVP, return a structured placeholder
        # Full implementation will wire to WorkshopFlux
        content = f"""# Research Report: {input.target or input.description[:50]}

## Executive Summary

This research explores {input.description}

**Depth**: {input.depth}
**Scope**: {input.scope or "Full scope"}

## Key Findings

*Scout's findings would be synthesized here*

## Detailed Analysis

*Sage's analysis would appear here*

## Recommendations

1. *First recommendation*
2. *Second recommendation*

## Sources

- Source 1
- Source 2

---
*Generated by Coalition Forge - Research Report Template*
"""

        return TaskOutput(
            content=content,
            format=OutputFormat.MARKDOWN,
            summary=f"Research report on: {input.target or input.description[:30]}",
            coalition_used=self.coalition_shape.required,
            handoffs=len(self.get_handoff_descriptions()),
            confidence=0.7,
            coverage=0.8
            if input.depth == "standard"
            else (0.5 if input.depth == "quick" else 0.95),
        )


# Singleton template instance
RESEARCH_REPORT_TEMPLATE = ResearchReportTask()

__all__ = ["ResearchReportTask", "RESEARCH_REPORT_TEMPLATE", "RESEARCH_REPORT_SHAPE"]
