"""
CounterAgent: Agent for: Build a simple counter that can increment and decrement

Auto-generated by the Metaphysical Forge.
"""

from .polynomial import CounterAgentPolynomial
from .service import CounterService

__all__ = [
    "CounterService",
    "CounterAgentPolynomial",
]
