/**
 * ShareModal - Crystal Export and Sharing Dialog
 *
 * Multiple export options for the daily crystal:
 * - Copy to clipboard (text)
 * - Download as Markdown (.md)
 * - Download as JSON
 * - Share link (placeholder for future)
 *
 * Design: Living Earth palette (bark background, sage accents)
 * Feel: The crystal deserves to be re-read - make sharing celebratory
 *
 * @see pilots/trail-to-crystal-daily-lab/PROTO_SPEC.md
 */

import { useState, useCallback, useMemo } from 'react';
import { type Crystal, type CompressionHonesty } from '@kgents/shared-primitives';
import { copyToClipboard, downloadMarkdown, downloadJSON } from '../../utils/download';

// =============================================================================
// Types
// =============================================================================

export interface ShareModalProps {
  /** The crystal to share */
  crystal: Crystal;

  /** Compression honesty details */
  honesty?: CompressionHonesty;

  /** Whether the modal is open */
  isOpen: boolean;

  /** Called when modal should close */
  onClose: () => void;
}

type ExportFormat = 'text' | 'markdown' | 'json' | 'link';
type ActionStatus = 'idle' | 'success' | 'error';

// =============================================================================
// Constants - Living Earth Palette
// =============================================================================

const COLORS = {
  bark: '#1C1917',
  lantern: '#FAFAF9',
  sand: '#A8A29E',
  clay: '#78716C',
  sage: '#A3E635',
  amber: '#FBBF24',
  rust: '#C2410C',
} as const;

// =============================================================================
// Format Converters
// =============================================================================

/**
 * Format a date for display.
 */
function formatDate(dateStr?: string): string {
  if (!dateStr) return 'Today';
  const date = new Date(dateStr);
  return date.toLocaleDateString('en-US', {
    weekday: 'long',
    month: 'long',
    day: 'numeric',
    year: date.getFullYear() !== new Date().getFullYear() ? 'numeric' : undefined,
  });
}

/**
 * Format honesty metrics for display.
 */
function formatHonesty(honesty?: CompressionHonesty): string {
  if (!honesty) return '';
  const parts: string[] = [];

  if (honesty.dropped_count > 0) {
    parts.push(`${honesty.dropped_count} marks set aside`);
  }
  if (honesty.galois_loss > 0) {
    parts.push(`${Math.round(honesty.galois_loss * 100)}% drift`);
  }

  return parts.length > 0 ? parts.join(' | ') : 'Nothing lost';
}

/**
 * Convert crystal to plain text format.
 */
export function crystalToText(crystal: Crystal, honesty?: CompressionHonesty): string {
  const lines: string[] = [];

  lines.push(`Daily Crystal - ${formatDate(crystal.timestamp)}`);
  lines.push('');
  lines.push(crystal.insight);
  lines.push('');
  lines.push(`Why this matters: ${crystal.significance}`);

  if (crystal.topics && crystal.topics.length > 0) {
    lines.push('');
    lines.push(`Topics: ${crystal.topics.join(', ')}`);
  }

  if (honesty) {
    lines.push('');
    lines.push(`Compression: ${formatHonesty(honesty)}`);
  }

  lines.push('');
  lines.push('---');
  lines.push('The day ends with warmth, not exhaustion.');
  lines.push('Generated by kgents Daily Lab');

  return lines.join('\n');
}

/**
 * Convert crystal to Markdown format.
 */
export function crystalToMarkdown(crystal: Crystal, honesty?: CompressionHonesty): string {
  const lines: string[] = [];

  lines.push(`# Daily Crystal - ${formatDate(crystal.timestamp)}`);
  lines.push('');
  lines.push('## Insight');
  lines.push('');
  lines.push(crystal.insight);
  lines.push('');
  lines.push('## Why This Matters');
  lines.push('');
  lines.push(crystal.significance);

  if (crystal.topics && crystal.topics.length > 0) {
    lines.push('');
    lines.push('## Topics');
    lines.push('');
    crystal.topics.forEach((topic) => {
      lines.push(`- ${topic}`);
    });
  }

  if (honesty) {
    lines.push('');
    lines.push('## Compression Details');
    lines.push('');
    lines.push(`- **Marks set aside**: ${honesty.dropped_count}`);
    lines.push(`- **Galois loss**: ${Math.round(honesty.galois_loss * 100)}%`);

    if (honesty.dropped_tags.length > 0) {
      lines.push(`- **Dropped categories**: ${honesty.dropped_tags.join(', ')}`);
    }
  }

  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('> *The day ends with warmth, not exhaustion.*');
  lines.push('');
  lines.push('*Generated by [kgents Daily Lab](https://kgents.dev)*');

  return lines.join('\n');
}

/**
 * Generate filename for crystal export.
 */
function generateFilename(crystal: Crystal): string {
  const date = new Date(crystal.timestamp);
  const dateStr = date.toISOString().split('T')[0]; // YYYY-MM-DD
  return `crystal-${dateStr}`;
}

// =============================================================================
// Sub-components
// =============================================================================

interface ExportOptionProps {
  icon: React.ReactNode;
  label: string;
  description: string;
  onClick: () => void;
  status: ActionStatus;
  disabled?: boolean;
}

function ExportOption({
  icon,
  label,
  description,
  onClick,
  status,
  disabled,
}: ExportOptionProps) {
  return (
    <button
      onClick={onClick}
      disabled={disabled || status === 'success'}
      className="flex items-start gap-4 w-full p-4 rounded-xl text-left transition-all hover:bg-white/5 disabled:opacity-50 disabled:cursor-not-allowed"
      style={{
        border: `1px solid ${status === 'success' ? COLORS.sage : COLORS.sage}33`,
        background: status === 'success' ? `${COLORS.sage}11` : 'transparent',
      }}
    >
      <div
        className="flex-shrink-0 w-10 h-10 rounded-lg flex items-center justify-center"
        style={{
          background: status === 'success' ? COLORS.sage : `${COLORS.sage}22`,
          color: status === 'success' ? COLORS.bark : COLORS.sage,
        }}
      >
        {status === 'success' ? <CheckIcon /> : icon}
      </div>
      <div className="flex-1 min-w-0">
        <div className="font-medium" style={{ color: COLORS.lantern }}>
          {status === 'success' ? `${label} - Done!` : label}
        </div>
        <div className="text-sm mt-0.5" style={{ color: COLORS.sand }}>
          {description}
        </div>
      </div>
    </button>
  );
}

interface PreviewSectionProps {
  crystal: Crystal;
  honesty?: CompressionHonesty;
}

function PreviewSection({ crystal, honesty }: PreviewSectionProps) {
  const previewText = useMemo(() => {
    const text = crystalToText(crystal, honesty);
    // Truncate for preview
    const maxLen = 300;
    return text.length > maxLen ? text.slice(0, maxLen) + '...' : text;
  }, [crystal, honesty]);

  return (
    <div
      className="p-4 rounded-xl text-sm font-mono whitespace-pre-wrap overflow-auto max-h-48"
      style={{
        background: `${COLORS.sage}11`,
        border: `1px solid ${COLORS.sage}22`,
        color: COLORS.sand,
      }}
    >
      {previewText}
    </div>
  );
}

// =============================================================================
// Icons
// =============================================================================

function ClipboardIcon() {
  return (
    <svg
      width="20"
      height="20"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
      <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
    </svg>
  );
}

function MarkdownIcon() {
  return (
    <svg
      width="20"
      height="20"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
      <polyline points="14 2 14 8 20 8" />
      <line x1="16" y1="13" x2="8" y2="13" />
      <line x1="16" y1="17" x2="8" y2="17" />
      <polyline points="10 9 9 9 8 9" />
    </svg>
  );
}

function JsonIcon() {
  return (
    <svg
      width="20"
      height="20"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
      <polyline points="14 2 14 8 20 8" />
      <path d="M8 13h2" />
      <path d="M8 17h2" />
      <path d="M14 13h2" />
      <path d="M14 17h2" />
    </svg>
  );
}

function LinkIcon() {
  return (
    <svg
      width="20"
      height="20"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71" />
      <path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71" />
    </svg>
  );
}

function CheckIcon() {
  return (
    <svg
      width="20"
      height="20"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="20 6 9 17 4 12" />
    </svg>
  );
}

function CloseIcon() {
  return (
    <svg
      width="20"
      height="20"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="18" y1="6" x2="6" y2="18" />
      <line x1="6" y1="6" x2="18" y2="18" />
    </svg>
  );
}

// =============================================================================
// Main Component
// =============================================================================

/**
 * ShareModal
 *
 * Modal dialog for sharing and exporting crystals.
 * Provides multiple export formats with a preview of what will be shared.
 */
export function ShareModal({ crystal, honesty, isOpen, onClose }: ShareModalProps) {
  const [actionStatus, setActionStatus] = useState<Record<ExportFormat, ActionStatus>>({
    text: 'idle',
    markdown: 'idle',
    json: 'idle',
    link: 'idle',
  });

  const setStatus = useCallback((format: ExportFormat, status: ActionStatus) => {
    setActionStatus((prev) => ({ ...prev, [format]: status }));
    // Auto-reset success after 3 seconds
    if (status === 'success') {
      setTimeout(() => {
        setActionStatus((prev) => ({ ...prev, [format]: 'idle' }));
      }, 3000);
    }
  }, []);

  // Copy to clipboard
  const handleCopyText = useCallback(async () => {
    const text = crystalToText(crystal, honesty);
    const success = await copyToClipboard(text);
    setStatus('text', success ? 'success' : 'error');
  }, [crystal, honesty, setStatus]);

  // Download as Markdown
  const handleDownloadMarkdown = useCallback(() => {
    const content = crystalToMarkdown(crystal, honesty);
    const filename = generateFilename(crystal);
    downloadMarkdown(content, filename);
    setStatus('markdown', 'success');
  }, [crystal, honesty, setStatus]);

  // Download as JSON
  const handleDownloadJSON = useCallback(() => {
    const data = {
      crystal,
      honesty,
      exported_at: new Date().toISOString(),
      format_version: '1.0',
    };
    const filename = generateFilename(crystal);
    downloadJSON(data, filename);
    setStatus('json', 'success');
  }, [crystal, honesty, setStatus]);

  // Generate shareable link (placeholder)
  const handleGenerateLink = useCallback(() => {
    // TODO: Implement actual link generation
    // For now, just copy a placeholder URL
    const placeholder = `https://kgents.dev/crystal/${crystal.crystal_id}`;
    copyToClipboard(placeholder);
    setStatus('link', 'success');
  }, [crystal.crystal_id, setStatus]);

  // Reset statuses when modal closes
  const handleClose = useCallback(() => {
    setActionStatus({
      text: 'idle',
      markdown: 'idle',
      json: 'idle',
      link: 'idle',
    });
    onClose();
  }, [onClose]);

  if (!isOpen) {
    return null;
  }

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4"
      onClick={handleClose}
    >
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-black/60 backdrop-blur-sm"
        aria-hidden="true"
      />

      {/* Modal */}
      <div
        className="relative w-full max-w-lg rounded-2xl overflow-hidden"
        style={{
          background: COLORS.bark,
          border: `1px solid ${COLORS.amber}33`,
          boxShadow: `0 25px 50px -12px rgba(0, 0, 0, 0.5)`,
        }}
        onClick={(e) => e.stopPropagation()}
        role="dialog"
        aria-modal="true"
        aria-labelledby="share-modal-title"
      >
        {/* Header */}
        <div
          className="flex items-center justify-between px-6 py-4 border-b"
          style={{ borderColor: `${COLORS.amber}22` }}
        >
          <div>
            <h2
              id="share-modal-title"
              className="text-lg font-semibold"
              style={{ color: COLORS.lantern }}
            >
              Share Your Crystal
            </h2>
            <p className="text-sm mt-0.5" style={{ color: COLORS.sand }}>
              A memory artifact worth keeping
            </p>
          </div>
          <button
            onClick={handleClose}
            className="p-2 rounded-lg hover:bg-white/10 transition-colors"
            style={{ color: COLORS.sand }}
            aria-label="Close"
          >
            <CloseIcon />
          </button>
        </div>

        {/* Content */}
        <div className="px-6 py-4 space-y-4">
          {/* Preview */}
          <div>
            <h3
              className="text-sm font-medium mb-2"
              style={{ color: COLORS.sand }}
            >
              Preview
            </h3>
            <PreviewSection crystal={crystal} honesty={honesty} />
          </div>

          {/* Export Options */}
          <div className="space-y-2">
            <h3
              className="text-sm font-medium mb-2"
              style={{ color: COLORS.sand }}
            >
              Export Options
            </h3>

            <ExportOption
              icon={<ClipboardIcon />}
              label="Copy to Clipboard"
              description="Plain text, ready to paste anywhere"
              onClick={handleCopyText}
              status={actionStatus.text}
            />

            <ExportOption
              icon={<MarkdownIcon />}
              label="Download Markdown"
              description="Formatted for notes, blogs, or docs"
              onClick={handleDownloadMarkdown}
              status={actionStatus.markdown}
            />

            <ExportOption
              icon={<JsonIcon />}
              label="Download JSON"
              description="Structured data for programmatic use"
              onClick={handleDownloadJSON}
              status={actionStatus.json}
            />

            <ExportOption
              icon={<LinkIcon />}
              label="Get Shareable Link"
              description="Coming soon - share with others"
              onClick={handleGenerateLink}
              status={actionStatus.link}
              disabled
            />
          </div>
        </div>

        {/* Footer */}
        <div
          className="px-6 py-4 border-t"
          style={{ borderColor: `${COLORS.sage}22` }}
        >
          <p
            className="text-xs text-center italic mb-3"
            style={{ color: COLORS.sand }}
          >
            A crystal worth sharing is a day worth living.
          </p>
          <div className="flex justify-end">
            <button
              onClick={handleClose}
              className="px-4 py-2 rounded-lg font-medium transition-colors hover:bg-white/10"
              style={{ color: COLORS.sand }}
            >
              Done
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

export default ShareModal;
