"""
CodeExporter - Generate Python code from pipeline.

Exports the composed pipeline as valid Python code that can be
run independently.
"""

from __future__ import annotations

from .types import PipelineComponent


class CodeExporter:
    """
    Export pipeline to Python code.

    Generates runnable Python code from the visual pipeline.
    """

    def __init__(self) -> None:
        pass

    def export(self, components: list[PipelineComponent]) -> str:
        """
        Export pipeline as Python code.

        Args:
            components: List of pipeline components

        Returns:
            Valid Python code as a string
        """
        if not components:
            return self._generate_empty_pipeline()

        code_lines = [
            '"""',
            "Generated pipeline from Forge.",
            "",
            "This code was auto-generated by the kgents Forge.",
            "You can run it directly or modify it as needed.",
            '"""',
            "",
            "from __future__ import annotations",
            "",
            "from bootstrap.types import Agent",
            "",
        ]

        # Import agents
        imports = self._generate_imports(components)
        code_lines.extend(imports)
        code_lines.append("")

        # Define the pipeline function
        code_lines.extend(
            [
                "async def run_pipeline(input_data):",
                '    """Run the composed pipeline."""',
                "    # Pipeline components:",
            ]
        )

        for i, component in enumerate(components):
            code_lines.append(f"    # {i + 1}. {component.spec.name}")

        code_lines.append("")

        # Initialize components
        for i, component in enumerate(components):
            agent_class = self._get_agent_class(component)
            code_lines.append(f"    agent_{i} = {agent_class}()")

        code_lines.append("")
        code_lines.append("    # Execute pipeline")
        code_lines.append("    current = input_data")

        for i in range(len(components)):
            code_lines.append(f"    current = await agent_{i}.invoke(current)")

        code_lines.extend(
            [
                "",
                "    return current",
                "",
                "",
                'if __name__ == "__main__":',
                "    import asyncio",
                "",
                "    # Example usage",
                "    async def main():",
                '        result = await run_pipeline("test input")',
                '        print(f"Result: {result}")',
                "",
                "    asyncio.run(main())",
            ]
        )

        return "\n".join(code_lines)

    def _generate_empty_pipeline(self) -> str:
        """Generate code for an empty pipeline."""
        return '''"""
Empty pipeline - no components added.

Add components in the Forge to generate a pipeline.
"""

import asyncio


async def run_pipeline(input_data):
    """Empty pipeline - returns input unchanged."""
    return input_data


async def main():
    """Example usage."""
    result = await run_pipeline("test input")
    print(f"Result: {result}")


if __name__ == "__main__":
    asyncio.run(main())
'''

    def _generate_imports(self, components: list[PipelineComponent]) -> list[str]:
        """
        Generate import statements for the pipeline.

        Args:
            components: List of components to import

        Returns:
            List of import statement lines
        """
        imports = []
        seen = set()

        for component in components:
            # Determine import path based on component type
            if component.spec.component_type.name == "AGENT":
                # Agent imports (e.g., from agents.a import AlethicAgent)
                letter = component.spec.id.split("-")[0]  # e.g., "a" from "a-alethic"
                class_name = f"{component.spec.name}Agent"
                import_line = f"from agents.{letter} import {class_name}"
            else:
                # Primitive imports (e.g., from agents.poly import GROUND)
                const_name = component.spec.name.upper()
                import_line = f"from agents.poly import {const_name}"

            if import_line not in seen:
                imports.append(import_line)
                seen.add(import_line)

        return imports

    def _get_agent_class(self, component: PipelineComponent) -> str:
        """
        Get the agent class name for a component.

        Args:
            component: The component

        Returns:
            Class name as string
        """
        if component.spec.component_type.name == "AGENT":
            return f"{component.spec.name}Agent"
        else:
            # For primitives, use the constant name
            return component.spec.name.upper()

    def export_to_file(
        self,
        components: list[PipelineComponent],
        filepath: str,
    ) -> None:
        """
        Export pipeline to a Python file.

        Args:
            components: List of pipeline components
            filepath: Path to write the file
        """
        code = self.export(components)
        with open(filepath, "w") as f:
            f.write(code)
