"""
BuildAAgent Polynomial: State machine definition.

States: IDLE, ACTIVE, ERROR
Initial: IDLE

Auto-generated by the Metaphysical Forge.
"""

from dataclasses import dataclass
from enum import Enum
from typing import Any


class BuildAAgentState(str, Enum):
    """States for BuildAAgent."""

    IDLE = "idle"
    ACTIVE = "active"
    ERROR = "error"


# State transition map
BUILDAAGENT_TRANSITIONS: dict[BuildAAgentState, list[BuildAAgentState]] = {
    BuildAAgentState.IDLE: [BuildAAgentState.ACTIVE],
    BuildAAgentState.ACTIVE: [BuildAAgentState.IDLE, BuildAAgentState.ERROR],
    BuildAAgentState.ERROR: [BuildAAgentState.IDLE],
}


@dataclass
class BuildAAgentPolynomial:
    """
    PolyAgent polynomial for BuildAAgent.

    Laws:
    - Identity: agent >> identity = agent
    - Graceful degradation: ERROR → IDLE always valid
    """

    state: BuildAAgentState = BuildAAgentState.IDLE

    def can_transition(self, to_state: BuildAAgentState) -> bool:
        """Check if transition is valid."""
        valid_transitions = BUILDAAGENT_TRANSITIONS.get(self.state, [])
        return to_state in valid_transitions

    def transition(self, to_state: BuildAAgentState) -> bool:
        """Attempt state transition. Returns True if successful."""
        if self.can_transition(to_state):
            self.state = to_state
            return True
        return False


__all__ = ["BuildAAgentState", "BuildAAgentPolynomial", "BUILDAAGENT_TRANSITIONS"]
