/**
 * BuildAVisualization - Agent for: Build a calculator
 *
 * Main visualization component for BuildAAgent.
 * Follows elastic-ui-patterns: density-aware layout.
 *
 * Auto-generated by the Metaphysical Forge Projector.
 *
 * @see services/forge/artisans/projector.py
 * @see docs/skills/elastic-ui-patterns.md
 */

import { useState, useCallback } from 'react';
import { Hammer, RefreshCw } from 'lucide-react';
import { useBuildAQuery } from './useBuildAQuery';
import { cn } from '@/lib/utils';
import type { Density } from '@/shell/types';

// =============================================================================
// Types
// =============================================================================

export interface BuildAVisualizationProps {
  /** Initial status data from PathProjection */
  status: BuildAStatusData | null;
  /** Current layout density */
  density: Density;
  /** Layout helpers */
  isMobile: boolean;
  isTablet: boolean;
  isDesktop: boolean;
  /** Refetch function from PathProjection */
  refetch: () => void;
}

export interface BuildAStatusData {
  name?: string;
  state?: string;
  description?: string;
}

// =============================================================================
// Component
// =============================================================================

export function BuildAVisualization({
  status: initialStatus,
  density,
  isMobile,
  isTablet: _isTablet,
  isDesktop: _isDesktop,
  refetch: parentRefetch,
}: BuildAVisualizationProps) {
  // AGENTESE hook for live data
  const manifest = useBuildAQuery();

  // Derive status from manifest or initial data
  const status = manifest.data?.state || initialStatus?.state || 'unknown';
  const name = manifest.data?.name || initialStatus?.name || 'BuildAAgent';
  const description = manifest.data?.description || initialStatus?.description || 'Agent for: Build a calculator';

  // Retry handler
  const handleRetry = useCallback(() => {
    manifest.refetch();
    parentRefetch();
  }, [manifest, parentRefetch]);

  // Density-adaptive styles
  const containerPadding = isMobile ? 'px-4 py-4' : 'px-6 py-8';
  const maxWidth = isMobile ? 'max-w-full' : 'max-w-4xl';
  const titleSize = isMobile ? 'text-xl' : 'text-2xl';

  return (
    <div className="min-h-screen bg-stone-50">
      {/* Header */}
      <header className="bg-white border-b border-stone-100">
        <div className={`${maxWidth} mx-auto ${containerPadding}`}>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Hammer className="w-6 h-6 text-amber-500" />
              <div>
                <h1 className={`${titleSize} font-serif text-stone-800`}>
                  {name}
                </h1>
                <p className="mt-1 text-sm text-stone-400">{description}</p>
              </div>
            </div>
            <button
              onClick={handleRetry}
              className="p-2 text-stone-400 hover:text-stone-600 transition-colors"
              title="Refresh"
            >
              <RefreshCw className={cn('w-5 h-5', manifest.isLoading && 'animate-spin')} />
            </button>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className={`${maxWidth} mx-auto ${containerPadding}`}>
        {/* Loading State */}
        {manifest.isLoading && !manifest.data && (
          <div className="flex items-center justify-center py-12">
            <RefreshCw className="w-6 h-6 text-stone-400 animate-spin" />
            <span className="ml-2 text-stone-500">Loading...</span>
          </div>
        )}

        {/* Error State */}
        {manifest.error && (
          <div className="p-4 bg-red-50 border border-red-100 rounded-lg">
            <div className="text-sm font-medium text-red-700">Error loading data</div>
            <p className="mt-1 text-xs text-red-500">{manifest.error.message}</p>
            <button
              onClick={handleRetry}
              className="mt-2 px-3 py-1 text-xs bg-red-100 text-red-700 rounded hover:bg-red-200"
            >
              Retry
            </button>
          </div>
        )}

        {/* Status Display */}
        {!manifest.isLoading && !manifest.error && (
          <div className="space-y-6">
            {/* State Card */}
            <div className="bg-white rounded-lg border border-stone-200 p-6">
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-lg font-medium text-stone-700">Current State</h2>
                <span className="px-2 py-1 text-xs bg-amber-100 text-amber-700 rounded-full">
                  {status}
                </span>
              </div>

              {/* State-specific content */}
          {status === 'idle' && (
            <div className="p-4 bg-stone-50 rounded-lg">
              <div className="text-sm font-medium text-stone-700">IDLE</div>
              <p className="mt-1 text-xs text-stone-400">
                Agent is in IDLE state
              </p>
            </div>
          )}
          {status === 'active' && (
            <div className="p-4 bg-stone-50 rounded-lg">
              <div className="text-sm font-medium text-stone-700">ACTIVE</div>
              <p className="mt-1 text-xs text-stone-400">
                Agent is in ACTIVE state
              </p>
            </div>
          )}
          {status === 'error' && (
            <div className="p-4 bg-stone-50 rounded-lg">
              <div className="text-sm font-medium text-stone-700">ERROR</div>
              <p className="mt-1 text-xs text-stone-400">
                Agent is in ERROR state
              </p>
            </div>
          )}
            </div>

            {/* Operations */}
            <div className="bg-white rounded-lg border border-stone-200 p-6">
              <h2 className="text-lg font-medium text-stone-700 mb-4">Operations</h2>
              <div className="flex flex-wrap gap-2">

            <button
              onClick={() => console.log('invoke')}
              className="px-3 py-2 text-sm bg-amber-100 text-amber-800 rounded-md hover:bg-amber-200 transition-colors"
              title="Main operation - implement based on intent"
            >
              Invoke
            </button>
              </div>
            </div>

            {/* Info Panel */}
            <div className="bg-stone-100 rounded-lg p-4">
              <p className="text-xs text-stone-500">
                States: IDLE, ACTIVE, ERROR |
                Operations: 1 |
                Generated by Metaphysical Forge
              </p>
            </div>
          </div>
        )}
      </main>

      {/* Footer */}
      <footer className="border-t border-stone-100 bg-white mt-16">
        <div className={`${maxWidth} mx-auto ${containerPadding} text-center`}>
          <p className="text-xs text-stone-300">BuildAAgent</p>
        </div>
      </footer>
    </div>
  );
}

export default BuildAVisualization;
